# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Node.js Package

on:
  release:
    types: [created]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run build
  publish-tarball:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        run: |
          REF="${{ github.ref_name }}"
          echo "build_version=${REF:1}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v3
        with:
            node-version: 22
            cache: 'npm'
      - run: |
          npm ci
          npm version ${{ github.ref_name }} --no-git-tag
          npm run build
          npm pack
      - name: Upload package
        uses: softprops/action-gh-release@v1
        with:
          files: garbee-iso8601-${{ env.build_version }}.tgz
  publish-packages:
    needs: publish-tarball
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '22.x'
            cache: 'npm'
            registry-url: 'https://registry.npmjs.org'
        - run: npm ci
        - run: npm version ${{ github.ref_name }} --no-git-tag
        - run: npm run build
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        - uses: actions/setup-node@v3
          with:
            registry-url: 'https://npm.pkg.github.com'
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
